name: Dispatch PR Events to Out-of-tree TestInfra

on:
  pull_request:

jobs:
  dispatch-event:
    if: github.repository_owner == 'cosdt'
    name: Dispatch events to the out-of-tree test infra repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print event info
        run: |
          echo "${{ toJson(github.event.pull_request) }}"

      - name: Create a repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.COSDT_BOT_TOKEN }}
          repository: cosdt/pytorch-integration-tests
          event-type: pytorch-event
          client-payload: |-
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.repository }}",
              "event_name": "${{ github.event_name }}",
              "pull_request": "${{ toJson(github.event.pull_request) }}"
            }
